nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.5.1.cjs

packageExtensions:
  "@emotion/server@*":
    dependencies:
      "@emotion/css": "^11.0.0-rc.0"

  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "^8.11.4"

  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "*"
      "vite": "*"
      "react": "^18.2.0"
      "react-dom": "^18.2.0"

  "@storybook/nextjs@*":
    dependencies:
      "@babel/core": "*"
      "webpack": "*"

  "babel-loader@*":
    dependencies:
      "webpack": "*"
