yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"

  "@storybook/nextjs@*":
    dependencies:
      "webpack": "*"
  axios@*:
    dependencies:
      debug: "*"
  debug@*:
    dependencies:
      supports-color: "8.1.1"
