nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.5.1.cjs

packageExtensions:
  "@emotion/server@*":
    dependencies:
      "@emotion/css": "*"

  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"

  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "*"
      "vite": "*"
      "react": "*"
      "react-dom": "*"

  "@storybook/nextjs@*":
    dependencies:
      "@babel/core": "*"
      "webpack": "*"

  "babel-loader@*":
    dependencies:
      "webpack": "*"

  "@emotion/babel-preset-css-prop@*":
    dependencies:
      "@babel/core": "*"
