import type { Metadata } from "next";

import Header from "@components/ui/Header";
import Footer from "@components/ui/Footer";
import Providers from "@components/query/Providers";

import Hydrate from "@components/query/hydrate/UserHydrate";

import "@styles/globals.css";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "SEOKO",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  function setBodyDatasetByTheme() {
    const prefersDarkFromMq = window.matchMedia("(prefers-color-scheme: dark)").matches;

    const persistedPreference = localStorage.getItem("theme");

    const colorMode = persistedPreference || (prefersDarkFromMq ? "dark" : "light");

    localStorage.setItem("theme", colorMode);

    document.body.dataset.theme = colorMode;
  }

  function ThemeScript() {
    const stringifyFn = String(setBodyDatasetByTheme);

    const fnToRunOnClient = `(${stringifyFn})()`;

    return <script dangerouslySetInnerHTML={{ __html: fnToRunOnClient }} />;
  }

  return (
    <html lang="ko">
      <body suppressHydrationWarning={true}>
        <ThemeScript />
        <div className="relative min-h-screen w-full bg-primary pb-36 transition-[background-color]">
          <Providers>
            <Hydrate>
              <Header />
              {children}
              <Footer />
            </Hydrate>
          </Providers>
        </div>
        <div id="modal" />
      </body>
    </html>
  );
};

export default RootLayout;
